import sys
import fileFunction.FunctionSave as FSave

# rien a expliquer ici ce n'est que des print

def menuTitle():
    print("\033[32m.d88888b                             oo                               dP          dP                         dP ")
    print("88.    \"'                                                             88          88                         88 ")
    print("`Y88888b. dP    dP 88d888b. dP   .dP dP dP   .dP .d8888b. 88d888b.    88 .d8888b. 88 .d8888b. 88d888b. .d888b88 ")
    print("      `8b 88    88 88'  `88 88   d8' 88 88   d8' 88'  `88 88'  `88    88 Y8ooooo. 88 88'  `88 88'  `88 88'  `88 ")
    print("d8'   .8P 88.  .88 88       88 .88'  88 88 .88'  88.  .88 88          88       88 88 88.  .88 88    88 88.  .88 ")
    print(" Y88888P  `88888P' dP       8888P'   dP 8888P'   `88888P' dP          dP `88888P' dP `88888P8 dP    dP `88888P8 \033[0m")
    print()
    print()
    print("                                                      \033[31mMENU")
    print("                                           Veuillez choisir une option")
    print("                                                  1 : New Game")
    print("                                                  2 : Load Game")
    print("                                                  3 : Score")
    print("                                                  4 : Historic\033[0m")

def gameWin(nomJoueur, tourJoueur, actionJoueur):
    print()
    print("-----------------VOUS AVEZ GAGNER------------------")
    print()	
	
    print("                         vv")
    print("                     vvv^^^^vvvvv")
    print("                 vvvvvvvvv^^vvvvvv^^vvvvv")
    print("        vvvvvvvvvvv^^^^^^^^^^^^^vvvvv^^^vvvvv")
    print("    vvvvvvv^^^^^^^^^vvv^^^^^^^vvvvvvvvvvv^^^vvv")
    print("  vvvv^^^^^^vvvvv^^^^^^^vv^^^^^^^vvvv^^^vvvvvv")
    print(" vv^^^^^^^^vvv^^^^^vv^^^^vvvvvvvvvvvv^^^^^^vv^")
    print(" vvv^^^^^vvvv^^^^^^vvvvv^^vvvvvvvvv^^^^^^vvvvv^")
    print("  vvvvvvvvvv^^^v^^^vvvvvv^^vvvvvvvvvv^^^vvvvvvvvv")
    print("   ^vv^^^vvvvvvv^^vvvvv^^^^^^^^vvvvvvvvv^^^^^^vvvvvv")
    print("     ^vvvvvvvvv^^^^vvvvvv^^^^^^vvvvvvvv^^^vvvvvvvvvv^v")
    print("        ^^^^^^vvvv^^vvvvv^vvvv^^^v^^^^^^vvvvvv^^^^vvvvv")
    print(" vvvv^^vvv^^^vvvvvvvvvv^vvvvv^vvvvvv^^^vvvvvvv^^vvvvv^")
    print("vvv^vvvvv^^vvvvvvv^^vvvvvvv^^vvvvv^v##vvv^vvvv^^vvvvv^v")
    print(" ^vvvvvv^^vvvvvvvv^vv^vvv^^^^^^_____##^^^vvvvvvvv^^^^")
    print("    ^^vvvvvvv^^vvvvvvvvvv^^^^/\@@@@@@\#vvvv^^^")
    print("         ^^vvvvvv^^^^^^vvvvv/__\@@@@@@\^vvvv^v")
    print("             ;^^vvvvvvvvvvv/____\@@@@@@\\vvvvvvv")
    print("             ;      \_  ^\|[  -:] ||--| | _/^^")
    print("             ;        \   |[   :] ||_/| |/")
    print("             ;         \\ ||___:]______/")
    print("             ;          \   ;=; /")
    print("             ;           |  ;=;|")
    print("             ;          ()  ;=;|")
    print("            (()          || ;=;|")
    print("                        / / \;=;\ ")
    print()
    print()
    print(f"Félicitation {nomJoueur}, vous avez gagner cette partie !")
    print(f"Vous avez gagné en fesant {tourJoueur} deplacements et {actionJoueur} actions")
    FSave.winAddScore(nomJoueur, tourJoueur, actionJoueur)
    FSave.addHistory(nomJoueur, "Win")
    sys.exit()

def gameOver(nomJoueur):
    print()
    print("-----------------GAME OVER------------------")
    print()	
    print("                      :::!~!!!!!:.")
    print("                  .xUHWH!! !!?M88WHX:.")
    print("                .X*#M@$!!  !X!M$$$$$$WWx:.")
    print("               :!!!!!!?H! :!$!$$$$$$$$$$8X:")
    print("              !!~  ~:~!! :~!$!#$$$$$$$$$$8X:")
    print("             :!~::!H!<   ~.U$X!?R$$$$$$$$MM!")
    print("             ~!~!!!!~~ .:XW$$$U!!?$$$$$$RMM!")
    print("               !:~~~ .:!M'T#$$$$WX??#MRRMMM!")
    print("               ~?WuxiW*`   `'#$$$$8!!!!??!!!")
    print("             :X- M$$$$       `'T#$T~!8$WUXU~")
    print("            :%`  ~#$$$m:        ~!~ ?$$$$$$")
    print("          :!`.-   ~T$$$$8xx.  .xWW- ~''##*'")
    print(".....   -~~:<` !    ~?T#$$@@W@*?$$      /`")
    print("W$@@M!!! .!~~ !!     .:XUW$W!~ `'~:    :")
    print("#'~~`.:x%`!!  !H:   !WM$$$$Ti.: .!WUn+!`")
    print(":::~:!!`:X~ .: ?H.!u '$$$B$$$!W:U!T$$M~")
    print(".~~   :X@!.-~   ?@WTWo('*$$$W$TH$! `")
    print("Wi.~!X$?!-~    : ?$$$B$Wu('**$RM!")
    print("$R@i.~~ !     :   ~$$$$$B$$en:``")
    print("?MXT@Wx.~    :     ~'##*$$$$M~")
    print()
    print()
    FSave.addHistory(nomJoueur, "Loose")

def printRegle():
    print()
    print("Ce matin, tu n'as pas été réveillé par les mouvements du navire (ton dernier souvenir est de t’être endormi sur la")
    print("confortable couchette de ta cabine à bord de l’Argo), mais par le bruit des vagues, la chaleur du soleil et le champ")
    print("des oiseaux...")
    print()
    print("Il semble que tu ne sois plus sur le bateau.")
    print()
    print("Tu es allongé sur une plage !")
    print()
    print("Tu te redresses doucement, et, un peu aveuglé par le soleil, tu regardes autour de toi. D'un côté la mer... de l'autre")
    print("un paysage sauvage, en partie steppe, en partie jungle. Assez loin, au-delà des arbres, tu penses apercevoir des")
    print("montagnes.")
    print()
    print("Tu fais un rapide bilan de ta situation : outre les vêtements que tu as sur toi (curieusement tes chaussures ne")
    print("semblent pas faire partie du lot 😉) tu trouves un sac à dos avec :")
    print("      une bouteille vide en verre,")
    print("      et un petit couteau multifonctions de bonne facture.")
    print()
    print("Un peu plus loin, posée sur une pierre, se trouve une mallette contenant :")
    print("      ton ordinateur portable (oui, il y a du réseau sur cette île),")
    print("      et un système de recharge photovoltaïque.")
    print()
    print("Enfin, glissée à l'intérieur du couvercle de la mallette se trouve une carte grossière plastifiée (voir en annexe).")
    print()
    print("Il est clair que tu n’es pas arrivé ici par hasard, ce n'est pas un naufrage, on t’a déposé sur cette plage.")
    print()
    print("Mais entre le moment où tu t’es endormi et ton réveil il y a quelques minutes, c'est le trou noir...")


def printTouche():
    print("Pour vous deplacer saisissez 'z' pour haut, 's' pour bas, 'q' pour gauche, 'd' pour droite vers une direction disponible ! ")

def debutDuJeux():
    print("------------")
    print("----Jeux----")
    print("------------")
    nomJoueur = str(input("Bonjour anonyme joueur, comment te prénommes-tu ? "))
    nomJoueur = nomJoueur.capitalize()
    print()
    print(f"Bonjour {nomJoueur} !")
    print()
    print("Bienvenue sur ce jeu de survie, l'objectif est de ce déplacer sur la carte et d'atteindre different point,")
    print("d'y accomplir des quètes, de les reussir afin de gagner des clefs, et enfin d'atteindre la porte mysterieuse,0")
    print("et de l'ouvrir a l'aide de vos clefs")
    print()
    print("Vous allez voir apparaitre une carte, les # * V ~ et † coresponde a des decorts, vous ne pouvez pas marcher dessus")
    print("# = bord du terrain, * = foret, V = montagne, † = desert")
    print("Pour vous deplacer le jeux vas vous demander ou vous souhaitez aller et vous devrez lui repondre")
    print("Vous pourrez repondre par 'z' pour haut, 's' pour bas, 'q' pour gauche, 'd' pour droite ")
    print("si vous souhaitez revoir vos touche saisissez 'touche'")
    print("pour revoir les règles, saississez 'regle'")
    return nomJoueur

def printMystere():
    print("                    ___")
    print("                   /III\\")
    print("                  /{= =}\__")
    print("                  |_\-/_|  \\")
    print("             jjs  |-| |-|{ |")
    print("                 /-_--_'-nn/")
    print("                nnn/  nnn|")

def printBag():
    print("                :*-")
    print("            =--+    =: *:")
    print("           -=           :-@")
    print("            *#:        :#")
    print("            -++:+=@*=@-")
    print("         -@:  #   #    *+")
    print("       -#-              -#")
    print("      #+                 -#")
    print("     @-                   #-")
    print("    @-                    *+")
    print("   #:                     ++")
    print("  **                      ++")
    print(" -#                       #-")
    print(" @                          +=")
    print("+=                           **")
    print("+=                            #")
    print(" #:                          #")
    print("  *@:                     +@#")
    print("     :#=*+++**=***+*+:     ")

def printRegleMystere():
    print()
    print("En haut de la falaise en bordure de forêt, pas très loin de la plage, \ntu découvres la statue d’un Sphinx avec une grosse clé en bronze posée sur les pattes.")
    print("Lorsque tu t’en approches, les yeux de la statue s’illuminent et une voix se fait entendre :")
    print("« Bonjour explorateur ! Pour ouvrir la porte de la montagne, atteindre le cœur de l’île \net rejoindre tes compagnons, tu devras tout d’abord prouver ta valeur individuelle \nen gagnant les 3 clés que tu obtiendras en relevant les défis appropriés. Ceci est le premier d’entre eux. »")
    print("Il est bien entendu impossible de prendre la clé (qui semble collée aux pattes du Sphinx) \ntant que le défi n’est pas gagné.")
    print("La voix poursuit : « 3 fois de suite, tu devras deviner le nombre que j’ai en tête, \ntu as 20 essais maximum pour tous les trouver, es-tu prêt ? »")

def printCesar():
    print("             / ,(//            /((. /         "    )
    print("           *((*                     ((          "  )
    print("         (( /*((/               ./((., /*         ")
    print("         ((,*(((                  ((/..((         ")
    print("       ,/*    *                   *.  . /(        ")
    print("        ((,,(/.                    /(( /(/        ")
    print("       ((/   /(                   ,// . //*       ")
    print("         ((,,  (( (            ( ((  /*//         ")
    print("         #(((. ( (/( (*    /( (/, (.*(((#         ")
    print("             ,**.,*  ##*  ((( *.* */.             ")
    print("             .(*  */( *(  (,.((   */           "   )
    print("                 ./* (      / */     ")

def printRegleCesar():
    print("Ce jeux est galere, demerde-toi mais si tu gagne tu aura la clef d'argent")

def printFizzBuzz():
    print("                      __------__")
    print("                    /~          ~\ ")
    print("                   |    //^\//^\|    ")      
    print("                 /~~\  ||  o| |o|:~\ ") 
    print("                | |6   ||___|_|_||:| ")     
    print("                 \__.  /      o  \/' ")   
    print("                  |   (       O   ) ")
    print("         /~~~~\    `\  \         /")
    print("        | |~~\ |     )  ~------~`\ ")
    print("       /' |  | |   /     ____ /~~~)\ ")
    print("      (_/'   | | |     /'    |    ( |")
    print("             | | |     \    /   __)/ \ ")
    print("             \  \ \      \/    /' \   `\ ")
    print("               \  \|\        /   | |\___|")
    print("                 \ |  \____/     | |")
    print("                 /^~>  \        _/ <")
    print("                |  |         \       \ ")
    print("                |  | \        \        \ ")
    print("                -^-\  \       |        )")
    print("                     `\_______/^\______/")

def printRegleFizz():
    print("Regarde il n'y a rien a faire")

def printAnanas():                                                
    print("                         %.                 ")      
    print("                @@@.   ####@  @&%%           ")     
    print("                  %#(@,#####@((@             ")     
    print("                ,@#@&(@##@@###@@##@           ")    
    print("                   @##&%%((%@###@             ")    
    print("                /@* @##@((((@##/ @@           ")    
    print("                   @(@#&(&&(#@%(@             ")    
    print("                  @#%((@&##@#(&/@@            ")    
    print("                    @#%@&##@@##@              ")    
    print("                   @%(@##%%@&%@(              ")    
    print("                @***#,@****,,@**@#(           ")    
    print("              @,,,@,,,,,%&,,,,,@(,,(,         ")    
    print("             @,(***&,,,(**&,,,#****%(@        ")    
    print("            @,/*,****@**,***&@**,**/,,%       ")    
    print("           #.,,,%*#,,,,#**#,,,,,/#.,,,#       ")    
    print("           @,,*%**/,,,,,&*%,,,,,%****/@#      ")    
    print("           @*,******@@*,******@,*****%.%      ")    
    print("           &,,/**&,,,,,@***(,,,,,,,&@*(.      ")    
    print("            &****%,,,,,,%**@,,,,,@****@       ")    
    print("            .(****,*@*********/,,@(**@        ")    
    print("              @(,,,,,,,,&**%,,,,,,,%@         ")    
    print("               ,%*&,,,*@*****/@/&*@           ")    
    print("                  @#,,%(****&.,@/           ")      
    print("                       .*/,   ")

def printCoconut():
    print("                         .&###########%&                 ")   
    print("                      &###################%(             ")   
    print("                    ########################%/           ")   
    print("                   ##########################%&          ")   
    print("                  #############################&         ")   
    print("              ,.       /########################         ")   
    print("                  *//*,      /###########%&##%@%         ")   
    print("         *    #(((,,,,,,,..,     /#######%&%&##&         ")   
    print("       .(    %((,,,,           & ,,,#######@%@           ")  
    print("       ((    %(,,,,              &,,,#######%*            ")  
    print("      (((#    (*,,                &   ####%*              ")  
    print("      (((((    (,,                /   ##%////////.#.      ")  
    print("      *((((&.,,,.*                (   ,///////((/////     ")  
    print("       %(((((@,,    #          (      ////////////&       ")  
    print("        #(((((((%(                  (*(//////(&.          ")  
    print("         %((((((((((((((##########%.###(((((##            ")  
    print("           @###((((((((((((#####%@    ,#(#%##(((#         ")   
    print("              /&#################%(         ,%#(###((#    ")       
    print("                                              (&(( ")

def printBouteille():
    print("            @  @                                            ")
    print("         @    @ @@@@@@@                                     ")
    print("          @@ &*          @                                  ")
    print("             .             .@                               ")
    print("            /             @   @                             ")
    print("             @          .   @   @                           ")
    print("               @     @    &   %    @                        ")
    print("                 @@@   @    @        ,@                     ")
    print("                    @@   %              @                   ")
    print("                      @#                  .@                ")
    print("                         @                   @              ")
    print("                           @.                  .@           ")
    print("                              @                   @         ")
    print("                                @.                @ @       ")
    print("                                   @                /       ")
    print("                                     @. @      %  @%        ")
    print("                                        @  @    @           ")
    print("                                           &@@.             ")


def printCookie():
    print("                      ,****************                     ")
    print("                .**************(|***********,               ")
    print("             ****||||||||****************(******            ")
    print("          .****||(#####%(|***********|(**********||         ")
    print("        ,******||######%%*****||||||||***||||##(|||(|       ")
    print("       ****|(***|||#%%#*****|||#####%||*||(#####%%**((.     ")
    print("     .|*********************||%#####%%**||(####%%#***((|    ")
    print("     ***************(********||(%%%##****||||||******(((|   ")
    print("    ****************(********************************|(((   ")
    print("   .****|||||||||********|||||||||******|**********|||((((  ")
    print("   ***|||#####%(|**((***||#######|*(|****************(((((  ")
    print("   ,**||(####%%%********||#####%%(*******************(((((  ")
    print("    ***|||#%%#**|(****(|*|||%#%(***********|||||||||(((((|  ")
    print("    *************||||||***************(**|||#####%#|(((((   ")
    print("     ****((***|||######||**********|(****||(#####%%(((((    ")
    print("      ********||######%%***************(**|||#%%%#(((((.    ")
    print("       *******|||%%%%%%******||||||***********((((((((      ")
    print("         **************|(**||######||******|((((((((        ")
    print("           |(*************||######%%***(((((((((((          ")
    print("              |(((|*||****|||%#%%%%((((((((((((             ")
    print("                  |(((((((((||(((((((((((((.                ")
    print("                         ,(((((((((*               ")








