import sys

def gameWin(nomJouteur):
    print()
    print("-----------------VOUS AVEZ GAGNER------------------")
    print()	
	
    print("                         vv")
    print("                     vvv^^^^vvvvv")
    print("                 vvvvvvvvv^^vvvvvv^^vvvvv")
    print("        vvvvvvvvvvv^^^^^^^^^^^^^vvvvv^^^vvvvv")
    print("    vvvvvvv^^^^^^^^^vvv^^^^^^^vvvvvvvvvvv^^^vvv")
    print("  vvvv^^^^^^vvvvv^^^^^^^vv^^^^^^^vvvv^^^vvvvvv")
    print(" vv^^^^^^^^vvv^^^^^vv^^^^vvvvvvvvvvvv^^^^^^vv^")
    print(" vvv^^^^^vvvv^^^^^^vvvvv^^vvvvvvvvv^^^^^^vvvvv^")
    print("  vvvvvvvvvv^^^v^^^vvvvvv^^vvvvvvvvvv^^^vvvvvvvvv")
    print("   ^vv^^^vvvvvvv^^vvvvv^^^^^^^^vvvvvvvvv^^^^^^vvvvvv")
    print("     ^vvvvvvvvv^^^^vvvvvv^^^^^^vvvvvvvv^^^vvvvvvvvvv^v")
    print("        ^^^^^^vvvv^^vvvvv^vvvv^^^v^^^^^^vvvvvv^^^^vvvvv")
    print(" vvvv^^vvv^^^vvvvvvvvvv^vvvvv^vvvvvv^^^vvvvvvv^^vvvvv^")
    print("vvv^vvvvv^^vvvvvvv^^vvvvvvv^^vvvvv^v##vvv^vvvv^^vvvvv^v")
    print(" ^vvvvvv^^vvvvvvvv^vv^vvv^^^^^^_____##^^^vvvvvvvv^^^^")
    print("    ^^vvvvvvv^^vvvvvvvvvv^^^^/\@@@@@@\#vvvv^^^")
    print("         ^^vvvvvv^^^^^^vvvvv/__\@@@@@@\^vvvv^v")
    print("             ;^^vvvvvvvvvvv/____\@@@@@@\vvvvvvv")
    print("             ;      \_  ^\|[  -:] ||--| | _/^^")
    print("             ;        \   |[   :] ||_/| |/")
    print("             ;         \\ ||___:]______/")
    print("             ;          \   ;=; /")
    print("             ;           |  ;=;|")
    print("             ;          ()  ;=;|")
    print("            (()          || ;=;|")
    print("                        / / \;=;\ ")
    print()
    print()
    print(f"Félicitation {nomJouteur}, vous avez gagner cette partie !")
    sys.exit()

def gameOver():
    print()
    print("-----------------GAME OVER------------------")
    print()	
    print("                      :::!~!!!!!:.")
    print("                  .xUHWH!! !!?M88WHX:.")
    print("                .X*#M@$!!  !X!M$$$$$$WWx:.")
    print("               :!!!!!!?H! :!$!$$$$$$$$$$8X:")
    print("              !!~  ~:~!! :~!$!#$$$$$$$$$$8X:")
    print("             :!~::!H!<   ~.U$X!?R$$$$$$$$MM!")
    print("             ~!~!!!!~~ .:XW$$$U!!?$$$$$$RMM!")
    print("               !:~~~ .:!M'T#$$$$WX??#MRRMMM!")
    print("               ~?WuxiW*`   `'#$$$$8!!!!??!!!")
    print("             :X- M$$$$       `'T#$T~!8$WUXU~")
    print("            :%`  ~#$$$m:        ~!~ ?$$$$$$")
    print("          :!`.-   ~T$$$$8xx.  .xWW- ~''##*'")
    print(".....   -~~:<` !    ~?T#$$@@W@*?$$      /`")
    print("W$@@M!!! .!~~ !!     .:XUW$W!~ `'~:    :")
    print("#'~~`.:x%`!!  !H:   !WM$$$$Ti.: .!WUn+!`")
    print(":::~:!!`:X~ .: ?H.!u '$$$B$$$!W:U!T$$M~")
    print(".~~   :X@!.-~   ?@WTWo('*$$$W$TH$! `")
    print("Wi.~!X$?!-~    : ?$$$B$Wu('**$RM!")
    print("$R@i.~~ !     :   ~$$$$$B$$en:``")
    print("?MXT@Wx.~    :     ~'##*$$$$M~")
    print()
    print()


def printBag():
    print("                :*-")
    print("            =--+    =: *:")
    print("           -=           :-@")
    print("            *#:        :#")
    print("            -++:+=@*=@-")
    print("         -@:  #   #    *+")
    print("       -#-              -#")
    print("      #+                 -#")
    print("     @-                   #-")
    print("    @-                    *+")
    print("   #:                     ++")
    print("  **                      ++")
    print(" -#                       #-")
    print(" @                          +=")
    print("+=                           **")
    print("+=                            #")
    print(" #:                          #")
    print("  *@:                     +@#")
    print("     :#=*+++**=***+*+:     ")