def gameOver():
    print()
    print("-----------------GAME OVER------------------")
    print()	
    print("                      :::!~!!!!!:.")
    print("                  .xUHWH!! !!?M88WHX:.")
    print("                .X*#M@$!!  !X!M$$$$$$WWx:.")
    print("               :!!!!!!?H! :!$!$$$$$$$$$$8X:")
    print("              !!~  ~:~!! :~!$!#$$$$$$$$$$8X:")
    print("             :!~::!H!<   ~.U$X!?R$$$$$$$$MM!")
    print("             ~!~!!!!~~ .:XW$$$U!!?$$$$$$RMM!")
    print("               !:~~~ .:!M'T#$$$$WX??#MRRMMM!")
    print("               ~?WuxiW*`   `'#$$$$8!!!!??!!!")
    print("             :X- M$$$$       `'T#$T~!8$WUXU~")
    print("            :%`  ~#$$$m:        ~!~ ?$$$$$$")
    print("          :!`.-   ~T$$$$8xx.  .xWW- ~''##*'")
    print(".....   -~~:<` !    ~?T#$$@@W@*?$$      /`")
    print("W$@@M!!! .!~~ !!     .:XUW$W!~ `'~:    :")
    print("#'~~`.:x%`!!  !H:   !WM$$$$Ti.: .!WUn+!`")
    print(":::~:!!`:X~ .: ?H.!u '$$$B$$$!W:U!T$$M~")
    print(".~~   :X@!.-~   ?@WTWo('*$$$W$TH$! `")
    print("Wi.~!X$?!-~    : ?$$$B$Wu('**$RM!")
    print("$R@i.~~ !     :   ~$$$$$B$$en:``")
    print("?MXT@Wx.~    :     ~'##*$$$$M~")
    print()
    print()