import sys

def gameWin(nomJouteur):
    print()
    print("-----------------VOUS AVEZ GAGNER------------------")
    print()	
	
    print("                         vv")
    print("                     vvv^^^^vvvvv")
    print("                 vvvvvvvvv^^vvvvvv^^vvvvv")
    print("        vvvvvvvvvvv^^^^^^^^^^^^^vvvvv^^^vvvvv")
    print("    vvvvvvv^^^^^^^^^vvv^^^^^^^vvvvvvvvvvv^^^vvv")
    print("  vvvv^^^^^^vvvvv^^^^^^^vv^^^^^^^vvvv^^^vvvvvv")
    print(" vv^^^^^^^^vvv^^^^^vv^^^^vvvvvvvvvvvv^^^^^^vv^")
    print(" vvv^^^^^vvvv^^^^^^vvvvv^^vvvvvvvvv^^^^^^vvvvv^")
    print("  vvvvvvvvvv^^^v^^^vvvvvv^^vvvvvvvvvv^^^vvvvvvvvv")
    print("   ^vv^^^vvvvvvv^^vvvvv^^^^^^^^vvvvvvvvv^^^^^^vvvvvv")
    print("     ^vvvvvvvvv^^^^vvvvvv^^^^^^vvvvvvvv^^^vvvvvvvvvv^v")
    print("        ^^^^^^vvvv^^vvvvv^vvvv^^^v^^^^^^vvvvvv^^^^vvvvv")
    print(" vvvv^^vvv^^^vvvvvvvvvv^vvvvv^vvvvvv^^^vvvvvvv^^vvvvv^")
    print("vvv^vvvvv^^vvvvvvv^^vvvvvvv^^vvvvv^v##vvv^vvvv^^vvvvv^v")
    print(" ^vvvvvv^^vvvvvvvv^vv^vvv^^^^^^_____##^^^vvvvvvvv^^^^")
    print("    ^^vvvvvvv^^vvvvvvvvvv^^^^/\@@@@@@\#vvvv^^^")
    print("         ^^vvvvvv^^^^^^vvvvv/__\@@@@@@\^vvvv^v")
    print("             ;^^vvvvvvvvvvv/____\@@@@@@\vvvvvvv")
    print("             ;      \_  ^\|[  -:] ||--| | _/^^")
    print("             ;        \   |[   :] ||_/| |/")
    print("             ;         \\ ||___:]______/")
    print("             ;          \   ;=; /")
    print("             ;           |  ;=;|")
    print("             ;          ()  ;=;|")
    print("            (()          || ;=;|")
    print("                        / / \;=;\ ")
    print()
    print()
    print("Félicitation " + str(nomJouteur) + ", vous avez gagner cette partie en 3 coups !")
    sys.exit()