def printRegle():
    print()
    print("Bienvenue sur ce jeux de survie, l'objectif est de ce déplacer sur la carte et d'atteindre different point,")
    print("d'y accomplir des quètes, de les reussir afin de gagner des clefs, et enfin d'atteindre la porte mysterieuse,0")
    print("et de l'ouvrir a l'aide de vos clefs")
    print()
    print("Vous allez voir apparaitre une carte, les # * V ~ et † coresponde a des decorts, vous ne pouvez pas marcher dessus")
    print("# = bord du terrain, * = foret, V = montagne, † = desert")
    print("Pour vous deplacer le jeux vas vous demander ou vous souhaitez aller et vous devrez lui repondre")
    print("Vous pourrez repondre par 'haut', 'bas', 'gauche', droite")
    print("si vous souhaitez revoir vos touche saisissez 'touche'")
    print("pour revoir les règles, saississez 'regle'")
    print()