nomJoueur = ""
avatar = "∇"
statSoif = 100
statFaim = 100
statSommeil = 100
# positionJoueurY = 2
# positionJoueurX = 13
positionJoueurY = 21
positionJoueurX = 3
sac = ["PC portable", "chargeur solaire", "couteau suisse", "carte", "bouteille d'eau"]
limitSac = 12
itemSlot = [["bouteille d'eau", 10], ["poireau", 10], ["noix de coco", 10], ["kit de cookie", 5]]
prevMoove = "commencer"
statutParti = "ok"
actionPossible = ["bouger", "dormir", "regle", "touche", "inventaire"]
directionPossible = ["s", "z", "q", "d"]
itemActionPossible = ["ramasser", "rien"]