# nomJoueur = ""
# avatar = "∇"
# statSoif = 100
# statFaim = 100
# statSommeil = 100
# positionJoueurY = 4
# positionJoueurX = 85
# sac = ["PC portable", "chargeur solaire", "couteau suisse", "carte", "bouteille d'eau"]
# limitSac = 12
# itemSlot = [["bouteille d'eau", 10], ["poireau", 10], ["noix de coco", 10], ["kit de cookie", 5]]
# prevMoove = "commencer"
# statutParti = "ok"
# actionPossible = ["bouger", "dormir", "regle", "touche", "inventaire"]
# directionPossible = ["s", "z", "q", "d"]
# itemActionPossible = ["ramasser", "rien"]
# reponseDebut = ["oui", "yes", "si"]


nomJoueur = 0
avatar = 0
statSoif = 0
statFaim = 0
statSommeil = 0
positionJoueurY = 0
positionJoueurX = 0
sac = 0
limitSac = 0
itemSlot = 0
prevMoove = 0
statutParti = 0
actionPossible = 0
directionPossible = 0
itemActionPossible = 0
reponseDebut = 0